### ISSUE TITLE
Expand permissions to all of Canonical

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/manager.assets.ubuntu.com#129]
Give the whole company permission to access the manager.

I think this isn't quite as simple as just changing the group from "canonical-content-people" to "canonical" in sso.py, because canonical is a private group so I think we need assistance from   someone who manages the SSO.

**Comment by sowasred2012** [comment]
I spoke to Daniel, and he has sorted this out for us.

**Comment by nottrobin** [comment]
Doesn't the code also need to change, here? https://github.com/canonical-web-and-design/manager.assets.ubuntu.com/blob/main/webapp/sso.py#L9
