### ISSUE TITLE
Dotrun errors out when trying to run project

### ISSUE THREAD

**Issue by mtruj013** [canonical-web-and-design/manager.assets.ubuntu.com#130]
`dotrun` fails with the following error: 

![Screenshot 2022-05-03 at 09 41 41](https://user-images.githubusercontent.com/17607612/166419116-a846477b-75c4-4ce5-bc69-cc072b43b115.png)

**Comment by sowasred2012** [comment]
@goulinkh do you have any ideas that could help us?
