### ISSUE TITLE
Underline on hover of title in header

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/manager.assets.ubuntu.com#38]
Similar to https://bugs.launchpad.net/hexr/+bug/1643980 the management interface has an eye-twitching underline that appears under the space when hovering.

**Comment by nottrobin** [comment]
I think this is only an issue for `jpg` vs `jpeg` so I changed the title to make it explicit.

![jpg-filters](https://user-images.githubusercontent.com/519935/30420906-f0fbcfa2-9932-11e7-87fe-c37f1a1daa9b.png)

**Comment by sowasred2012** [comment]
@sparkiegeek I don't see this, is it still a problem for you?

**Comment by sparkiegeek** [comment]
wow, 4 year old bug - nope seems to no longer be showing
